import { Cardstatus, AbilityCard, targetType, effectType } from '../../api/types';
let AbilityCardPool: AbilityCard[];

export default AbilityCardPool = [
    {
        Title: 'Spear',
        Catagory: 'weapon',
        Level: 2,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack2',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Crossbow',
        Catagory: 'weapon',
        Level: 5,
        Cost: 6,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack2',
            userPrompt: false,
        },
        PassiveEffect: {
            target: targetType.ActiveHero,
            cb: 'passiveWhenMonsterDefeatedDraw1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Dagger',
        Catagory: 'weapon',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack1',
            userPrompt: false,
        },

        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Sling',
        Catagory: 'weapon',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack1Ability1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Broadsword',
        Catagory: 'weapon',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            cb: 'addAttack1',
            target: targetType.ActiveHero,
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Mana_Potion',
        Catagory: 'item',
        Level: 1,
        Cost: 4,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addHealth1Ability1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Bracelet',
        Catagory: 'item',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAbility1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Acid_Hail',
        Catagory: 'spell',
        Level: 1,
        Cost: 2,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Jewel',
        Catagory: 'item',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAbility1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Daydream',
        Catagory: 'spell',
        Level: 1,
        Cost: 2,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAbility1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Awakening',
        Catagory: 'spell',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAbility1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Torrent',
        Catagory: 'spell',
        Level: 1,
        Cost: 4,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack1Draw1',
            userPrompt: true,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Torment',
        Catagory: 'spell',
        Level: 1,
        Cost: 2,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'draw1lose1',
            userPrompt: true,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Solitude',
        Catagory: 'spell',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttack1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Holy_Tempest',
        Catagory: 'spell',
        Level: 1,
        Cost: 4,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'chooseHealth1Ability1',
            userPrompt: true,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Eviction',
        Catagory: 'spell',
        Level: 1,
        Cost: 5,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'removeLocation1',
            userPrompt: true,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Imitation_Rituals',
        Catagory: 'spell',
        Level: 1,
        Cost: 3,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'chooseAbility1Draw1',
            userPrompt: true,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Duraina',
        Catagory: 'friend',
        Level: 1,
        Cost: 4,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttackHealth1ForAll',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
    {
        Title: 'Jacquelyn',
        Catagory: 'friend',
        Level: 1,
        Cost: 2,
        ActiveEffect: {
            target: targetType.ActiveHero,
            cb: 'addAttackHealth1ForAll',
            userPrompt: false,
        },
        PassiveEffect: {
            target: targetType.ActiveHero,
            cb: 'passiveWhenMonsterDefeatedAbility1',
            userPrompt: false,
        },
        CardStatus: Cardstatus.FaceDown,
    },
];
